fix(cb-133): redirect on the / home page after successful creation of contract, and delete contract's fields
Rock-n-Block/C-block pull request #50
Opened 2022-03-10 23:04 UTC by Kamikozz

2022-03-14 13:05 UTC, ValnetineKul requested changes

2022-03-14 13:05 UTC, ValnetineKul commented on src/components/Preview/Preview.tsx
> +      }, 3000);
Was it a requirement to close modal in 3 seconds?

2022-03-14 13:05 UTC, ValnetineKul commented on src/pages/WillContractPreview/WillContractPreview.tsx
> +    // dispatch(deleteContract({
delete

2022-03-14 13:26 UTC, Kamikozz commented on src/components/Preview/Preview.tsx
> +      }, 3000);
Nope, but it would be great if a person can see the notification text before it closes

2022-03-15 09:43 UTC, ValnetineKul commented on src/components/Preview/Preview.tsx
> +      }, 3000);
I mean if its a modal, why force close, user can close it by himself

2022-03-15 09:52 UTC, Kamikozz commented on src/components/Preview/Preview.tsx
> +      }, 3000);
Ah, sorry. That is done to prevent re-opening the modal after redirect and go back to preview page (by navigation of the site)

2022-03-15 10:03 UTC, merged